### ISSUE TITLE
[FEATURE REQUEST] Website to download people's journeys

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#1]
A HTML site, which will display all the journey's by coders, that if tapped, you can view the persons journey in the browser, choose to download a txt file of it.

It's a little of the concepts from [Linkfree](http://linkfree.eddiehub.org/) but not really.

**Comment by Adarsh-jaiss** [comment]
-- that's a great idea man! 
Loved it! 
Let's do this 😃😃

But I don't know web development, so we have to bring out some open source web developers 🙂
Who can contribute to this project

**Comment by Adarsh-jaiss** [comment]
I you know anyone, kindly refer them to contribute 😃

**Comment by KendallDoesCoding** [comment]
> -- that's a great idea man! Loved it! Let's do this 😃😃
> 
> But I don't know web development, so you can work on that or we have to bring out some open source web developers 🙂 Who can contribute to this project

I can code the HTML, CSS part of it, the suggestion only needs that much, I'm not that good at JS, I'll get to work on this during the week, but for now I suggest you learn some Web Dev, in your free time!

**Comment by Adarsh-jaiss** [comment]
-- okay , i am gonna try to manage to learn it !

-- wait a minute,  i have to  find someone who knows javascript well and can work with us on this project :)

**Comment by KendallDoesCoding** [comment]
> -- okay , i am gonna try to manage to learn it !
> 
> -- wait a minute, i have to find someone who knows javascript well and can work with us on this project :)

ok cool!

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Please refer to https://github.com/Adarsh-jaiss/journey-book/discussions/19

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Okay, I need you to decide on the following:

**Options**
a) Web Dev to individually add a page for every persons journey, to download the stuff
b) Web Dev to code a bot to automatically, link the stuff from .json/.md files into the website (this will take much more work)

I can work on a for now, the issue with a is I need to be available anytime a user adds a journey, with b it takes time in the beginning but the end result is great, but idk how to do b, I can do a as that is basic.

**Comment by Adarsh-jaiss** [comment]
we should go for the 2nd one because it will save a lot of time in future

**Comment by Adarsh-jaiss** [comment]
> > we should go for the 2nd option (b) because it will save a lot of time in future
> 
> True, I can't do that tho , as I said.. I can work on the basic design of the site though.

tell me one thing, is there any way that in future if we want to migrate from option (A) to(B) . so is that possible or not?

**Comment by KendallDoesCoding** [comment]
> > > we should go for the 2nd option (b) because it will save a lot of time in future
> > 
> > 
> > True, I can't do that tho , as I said.. I can work on the basic design of the site though.
> 
> tell me one thing, is there any way that in future if we want to migrate from option (A) to(B) . so is that possible or not?

Idrk, but yeah ig.

**Comment by Adarsh-jaiss** [comment]
> I would still suggest we do b first, but that will need other help, as I know how to do a, you don't know web dev

then let's do "B". I have messaged a web developer. waiting for her reply.

here's is here id: https://github.com/riti2409

**Comment by KendallDoesCoding** [comment]
> > I would still suggest we do b first, but that will need other help, as I know how to do a, you don't know web dev
> 
> then let's do "B". I have messaged a web developer. waiting for her reply.
> 
> here's is her id: https://github.com/riti2409

Ok cool! You can message @TechStudent10 too on their README.md repo in discussions tab, they may be down to help, but their a little busy these days!

**Comment by KendallDoesCoding** [comment]
> > > I would still suggest we do b first, but that will need other help, as I know how to do a, you don't know web dev
> > 
> > 
> > then let's do "B". I have messaged a web developer. waiting for her reply.
> > here's is her id: https://github.com/riti2409
> 
> Ok cool! You can message @TechStudent11 too on their README.md repo in discussions tab, they may be down to help, but their a little busy these days with school, etc!

You can also contact @aliraza944 for JS help.

**Comment by Adarsh-jaiss** [comment]
-- thanks for sharing 
-- I am going to approach them tomorrow 🙂

**Comment by KendallDoesCoding** [comment]
> -- thanks for sharing -- I am going to approach them tomorrow 🙂

Ok! You can tell them, I recommended them to you!

**Comment by Adarsh-jaiss** [comment]
I have approached @Techstudent11 for help, waiting for his reply🙂

**Comment by KendallDoesCoding** [comment]
> I have approached @TechStudent11 for help, waiting for his reply🙂

Yup, got a email notific on that.

**Comment by KendallDoesCoding** [comment]
Created the "website" branch in this repo to work on this. @Adarsh-jaiss Please host that branch on Netlify, or I think I may be able to do so.

**Comment by KendallDoesCoding** [comment]
> Created the "website" branch in this repo to work on this. @Adarsh-jaiss Please host that branch on Netlify, or I think I may be able to do so.

No, I can't.. Please host that branch on netlify, if you need any help you can reach out.

**Comment by Adarsh-jaiss** [comment]
Can you tell me how can I do that?

**Comment by Adarsh-jaiss** [comment]
Tell me the steps or processes

**Comment by KendallDoesCoding** [comment]
> Can you tell me how can I do that?

Sure, but I've already setup my account so it may be wrong

- Sign Up to https://app.netlify.com/
- Go to https://app.netlify.com/start
- Tap GitHub
- Autorize Netlify to access your github
- It will take you to Netlify, tap this repo name
- Set branch to deploy as "website
- Go down to the page and say deploy site

Then, the site will deploy and any commits made to "website" will auto be deployed, although to change the domain name there are further instructions, for now you do the above.

**Comment by Adarsh-jaiss** [comment]
Okay -- link me the branch

**Comment by KendallDoesCoding** [comment]
> Okay -- link me the branch

Netlify already knows the branches, you just need to tap where it says "main" under Branch and set it to website.

**Comment by Adarsh-jaiss** [comment]
Okay

**Comment by Adarsh-jaiss** [comment]
What should I fill in the my first project section

**Comment by KendallDoesCoding** [comment]
> What should I fill in the my first project section

Please send ss,

**Comment by Adarsh-jaiss** [comment]
Documentation & knowledge base
Or blog

**Comment by Adarsh-jaiss** [comment]
Or something else

**Comment by KendallDoesCoding** [comment]
> Documentation & knowledge base Or blog

Send screenshot, can't understand.

**Comment by Adarsh-jaiss** [comment]
![Uploading IMG_20220310_121449.jpg…]()

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Please come here: https://github.com/Adarsh-jaiss/journey-book/discussions/24

**Comment by KendallDoesCoding** [comment]
> [](https://github.com/Adarsh-jaiss/journey-book/issues/1)Uploading IMG_20220310_121449.jpg…


Think you need to wait for it to upload then comment xD

**Comment by TechStudent11** [comment]
So you want to be able to do is to download whatever "journey" a user has created.

So a couple of things
1. Are you willing to
    1. build a server?
    2. deal with the client/server model?
    3. build an entire database?

If so, I would be willing to help.

**Comment by Adarsh-jaiss** [comment]
Yeah, that is all we want 😃

**Comment by Adarsh-jaiss** [comment]
> So you want to be able to do is to download whatever "journey" a user has created.
> 
> So a couple of things
> 
> 1. Are you willing to
>    
>    1. build a server?
>    2. deal with the client/server model?
>    3. build an entire database?
> 
> If so, I would be willing to help.

Let's do this guies 😃😃😃😃

**Comment by KendallDoesCoding** [comment]
> > So you want to be able to do is to download whatever "journey" a user has created.
> > So a couple of things
> > 
> > 1. Are you willing to
> >    
> >    1. build a server?
> >    2. deal with the client/server model?
> >    3. build an entire database?
> > 
> > If so, I would be willing to help.
> 
> Let's do this guies 😃😃😃😃

I'm a noob, can only do basic HTML, CSS, can't do any of this, sadly :(

**Comment by Adarsh-jaiss** [comment]
@KendallDoesCoding  it's okay bro 🤜 :) 

- let's divide the work according to our skill sets, so it will be easy to work on🙂

**Comment by TechStudent11** [comment]
Ok then here's what you need to do (I am not going to code the entire thing for you).

---

1. Learn how to create a server in your preferred language (JavaScript, Python, Ruby on Rails, etc.)
2. Connect a database (i.e MongoDB, Postgres, SQLite, etc.) to your server
3. Connect the frontend (in this case, your website) to the backend (your server).

---

You can then download the journeys by sending the user to a link on your server to download the journey in the database. You would also need to update your code to store and retrieve user's journeys using your server/database. You also need to handle differentiating different users (e.g creating users, session ID's, etc.).

---

Now some recommendations;

As for the server, you might want to get started using JavaScript, more specifically NodeJS. If you don't know what that is, here's my video on NodeJS and a more detailed one by Fireship:

My video: https://www.youtube.com/watch?v=ykvbkhZ6et0
Fireship's video: https://www.youtube.com/watch?v=ENrzD9HAZK4

You should use the Express library for the server.

---

For the database, you have two options. Number 1, an SQL database. SQL (if you don't know) stands for Structured Query Language and is used in a lot of server and database application. Your second option is a NoSQL or JSON (**J**ava**S**cript **O**bject **N**otation) database. Two example of a NoSQL database are MongoDB and Firebase. They both use JSON and are much easier to work with because they require little work on the server side.

---

### Some resources to get you started

**Server software**
Express - https://expressjs.com/
NodeJS - https://nodejs.org/

**Databases**
MongoDB - https://www.mongodb.com/
Fireship - https://console.firebase.google.com

**Hosting (you'll need it for the server, you could also use [Firebase Hosting](https://firebase.google.com/docs/hosting))**
Heroku - https://heroku.com
Netlify - https://netlify.com

---

Happy Coding.

**Comment by KendallDoesCoding** [comment]
> Ok then here's what you need to do (I am not going to code the entire thing for you).
> 
> 1. Learn how to create a server in your preferred language (JavaScript, Python, Ruby on Rails, etc.)
> 2. Connect a database (i.e MongoDB, Postgres, SQLite, etc.) to your server
> 3. Connect the frontend (in this case, your website) to the backend (your server).
> 
> You can then download the journeys by sending the user to a link on your server to download the journey in the database. You would also need to update your code to store and retrieve user's journeys using your server/database. You also need to handle differentiating different users (e.g creating users, session ID's, etc.).
> 
> Now some recommendations;
> 
> As for the server, you might want to get started using JavaScript, more specifically NodeJS. If you don't know what that is, here's my video on NodeJS and a more detailed one by Fireship:
> 
> My video: https://www.youtube.com/watch?v=ykvbkhZ6et0 Fireship's video: https://www.youtube.com/watch?v=ENrzD9HAZK4
> 
> You should use the Express library for the server.
> 
> For the database, you have two options. Number 1, an SQL database. SQL (if you don't know) stands for Structured Query Language and is used in a lot of server and database application. Your second option is a NoSQL or JSON (**J**ava**S**cript **O**bject **N**otation) database. Two example of a NoSQL database are MongoDB and Firebase. They both use JSON and are much easier to work with because they require little work on the server side.
> 
> ### Some resources to get you started
> **Server software** Express - https://expressjs.com/ NodeJS - https://nodejs.org/
> 
> **Databases** MongoDB - https://www.mongodb.com/ Fireship - https://console.firebase.google.com
> 
> **Hosting (you'll need it for the server, you could also use [Firebase Hosting](https://firebase.google.com/docs/hosting))** Heroku - https://heroku.com Netlify - https://netlify.com
> 
> Happy Coding.

This seems like a lot of work.

> Hosting (you'll need it for the server, you could also use [Firebase Hosting](https://firebase.google.com/docs/hosting))
Heroku - https://heroku.com/
Netlify - https://netlify.com/


It's already hosted on netlify, we just need to update the domain.


@Adarsh-jaiss You can invite more people to work on this based on their skill set, if you don't want to do every thing, but for now, I can help you with the HTML, CSS, @TechStudent11 can help you when you do the listed by him for the JS.

**Comment by Adarsh-jaiss** [comment]
Okay great :) 
Now here's the roadmap and i am going to find someone who can do this with us :)

**Comment by KendallDoesCoding** [comment]
Any update on this @Adarsh-jaiss ?

**Comment by KendallDoesCoding** [comment]
> Some are interested but they are busy because of their semester exams. After exams they will work on this.
> 
> -- i have found someone who can create database And code javascript for the website :)
> 
> -- i am going to remind them about this :)
> 
> @KendallDoesCoding

Ok cool!

Even I'm busy with my final exams, will be free on the 9th April!

**Comment by TechStudent11** [comment]
If you really just get stuck, I could provide some help.

**Comment by Adarsh-jaiss** [comment]
-- sounds great :)

**Comment by Gbeka** [comment]
Hi, guys! I am currently studying the React. I didn't work with the database. Is it possible to learn this in a short time? And I have a question, what exactly am I need to do? I'll try

**Comment by Adarsh-jaiss** [comment]
Can you write some javascript code for the website since @KendallDoesCoding will take care of html and css. And for the rest @TechStudent11  can help us Or guide us🙂

**Comment by KendallDoesCoding** [comment]
@Gbeka Are you free to begin work now?

**Comment by Adarsh-jaiss** [comment]
@vikasganiga05 can you code javascript for this project 😃 ?

**Comment by vikasganiga05** [comment]
> @vikasganiga05 can you code javascript for this project smiley ?

Hi, I love to work on the JavaScript part. I will read this thread very soon. Vanilla JS or any framework?
Thank You :pray:

**Comment by KendallDoesCoding** [comment]
> > @vikasganiga05 can you code javascript for this project smiley ?
> 
> Hi, I love to work on the JavaScript part. I will read this thread very soon. Vanilla JS or any framework? Thank You 🙏

vanilla JS

**Comment by vikasganiga05** [comment]
Hi, Sorry for the late reply. I like to work on this project. Let's start a new [discussion](https://github.com/Adarsh-jaiss/journey-book/discussions/new) on this topic.

**Comment by Adarsh-jaiss** [comment]
-- @KendallDoesCoding  will help you with that 😃

**Comment by KendallDoesCoding** [comment]
> Hi, Sorry for the late reply. I like to work on this project. Let's start a new [discussion](https://github.com/Adarsh-jaiss/journey-book/discussions/new) on this topic. Where we can discuss what features to be implemented and other stuff.

Yup ofc, should I make the discussion or will you?

**Comment by vikasganiga05** [comment]
> > Hi, Sorry for the late reply. I like to work on this project. Let's start a new [discussion](https://github.com/Adarsh-jaiss/journey-book/discussions/new) on this topic. Where we can discuss what features to be implemented and other stuff.
> 
> Yup ofc, should I make the discussion or will you?

Please can you create a discussion?

**Comment by KendallDoesCoding** [comment]
> > > Hi, Sorry for the late reply. I like to work on this project. Let's start a new [discussion](https://github.com/Adarsh-jaiss/journey-book/discussions/new) on this topic. Where we can discuss what features to be implemented and other stuff.
> > 
> > 
> > Yup ofc, should I make the discussion or will you?
> 
> Please can you create a discussion?

Sure! I made #32, hope that works!

**Comment by vikasganiga05** [comment]
> > > > Hi, Sorry for the late reply. I like to work on this project. Let's start a new [discussion](https://github.com/Adarsh-jaiss/journey-book/discussions/new) on this topic. Where we can discuss what features to be implemented and other stuff.
> > > 
> > > 
> > > Yup ofc, should I make the discussion or will you?
> > 
> > 
> > Please can you create a discussion?
> 
> Sure! I made #32, hope that works!

Thanks You :pray:

**Comment by KendallDoesCoding** [comment]
@shourgamer2 - do you know web dev/JS, can you help me or @vikasganiga05 with this website?

**Comment by cojored** [comment]
I would be able to help out. If you have discord I respond fastest on discord add me cojored#2177.

**Comment by KendallDoesCoding** [comment]
> I would be able to help out. If you have discord I respond fastest on discord add me cojored#2177.

Hi. We have made a discussion (#32 ) do discuss on this. While discord works, I and others ig prefer to talk via GitHub Discussions, as it keeps everyone up to date, including new contributors, who may not have discord, and have just found the project, if you get what I mean :)
