### ISSUE TITLE
Query on Favicon

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#106]
After merging #105 , this favicon is showing on the home page: 
![image](https://user-images.githubusercontent.com/84712013/183033986-90bae0bc-ef61-41f1-9656-dcc6c5d3a3ab.png)
 
But, once the vote #99 is done today, I am supposed to be changing the favicon, but how can I do it if this is the current favicon?

Please help @vikasganiga05

**Comment by vikasganiga05** [comment]
I added that favicon temporarily. Once vote #99 is completed then you can replace the `favicon.ico` file with the favicon won in the vote.

If the favicon is `.ico`, then no need to change the `index.html` file. If it's a `.png` then make the following change to the `index.html` file.

```diff
- <link id="favicon" rel="icon" href="./favicon.ico" />
+ <link id="favicon" rel="icon" type="image/png" href="./favicon.png" />
```

**Comment by KendallDoesCoding** [comment]
> I added that favicon temporarily. Once vote #99 is completed then you can replace the `favicon.ico` file with the favicon won in the vote.
> 
> If the favicon is `.ico`, then no need to change the `index.html` file. If it's a `.png` then make the following change to the `index.html` file.
> 
> ```diff
> - <link id="favicon" rel="icon" href="./favicon.ico" />
> + <link id="favicon" rel="icon" type="image/png" href="./favicon.png" />
> ```
> 
> I hope this helped you. If you have any queries please let me know 🙂 Thank You.

Ok. Thanks for your help Vikas!
