### ISSUE TITLE
[URGENT] Journey not updating on Website

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#112]
The token seems to be "expired" or removed. I hope you had set the token to never expire once it was created @Adarsh-jaiss . Hence, the journey's are not updating on the website, which is really BAD, please fix at the earliest @Adarsh-jaiss.

cc: @vikasganiga05

**Comment by KendallDoesCoding** [comment]
"authorization":"token [REDACTED]"}}}

SOURCE: https://github.com/collab-community/journey-book/runs/7747975742?check_suite_focus=true

**Comment by Adarsh-jaiss** [comment]
I haven't created this token. It was created by you or vikas

**Comment by KendallDoesCoding** [comment]
> I haven't created this token. It was created by you or vikas

Oh, request you to please create this token. @vikasganiga05 will guide you.

**Comment by Adarsh-jaiss** [comment]
Kindly explain me the process and I will create it ASAP! , 
PLEASE ADD WHAT TO CHOOSE WHILE CREATING ACCESS TOKEN TOO

**Comment by KendallDoesCoding** [comment]
> Kindly explain me the process and I will create it ASAP! , @vikasganiga05 PLEASE ADD WHAT TO CHOOSE WHILE CREATING ACCESS TOKEN TOO

even im not sure, lemme see.

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss choose everything generate the token and put it in BOT_ACCESS_TOKEN environment secret and see if it works, if it doesn't then idk

**Comment by KendallDoesCoding** [comment]
Fixed yesterday, although now it's on my token instead of @Adarsh-jaiss.
