### ISSUE TITLE
[DOCS] Fix documentation links in the readme file

### ISSUE THREAD

**Issue by AbbeyIT** [collab-community/journey-book#128]
**Describe the bug**
A 404 error has occurred when accessing all the links in the documentation, such as "What is Journey Book?"

**To Reproduce**
1. Go to 'README.md'
2. Scroll down to 'Documentation'
3. Click on 'What is Journey Book?', 'Why We Created this Project!', 'Share Your Experience NOW!!!', 'What Should My Journey Include?'

**Expected behavior**
It is supposed to show the page which consists of the documentation of the said topics.

**Screenshots**
![image](https://user-images.githubusercontent.com/93916892/185508047-9c19fc4f-2898-4ace-832e-7668ef54b76c.png)

**Desktop:**
 - Browser: OperaGX, Firefox

**Comment by vikasganiga05** [comment]
Hi @AbbeyIT , Thanks for reporting the bug. Please let us know if you like to work on this issue.

**Comment by AbbeyIT** [comment]
HI @vikasganiga05 I would like to work on this issue. Please assign it to me. Thank you.

**Comment by vikasganiga05** [comment]
> HI @vikasganiga05 I would like to work on this issue. Please assign it to me. Thank you.

Sorry for the late reply. I assigned it to you.
