### ISSUE TITLE
[BUG] Low contrast text on light theme

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/journey-book#137]
**Describe the bug**
In the light theme, some text on the website is hard to read.

**To Reproduce**
1. Go to [https://collab-community.github.io/journey-book/](https://collab-community.github.io/journey-book/)
2. If the site theme is dark switch to light by clicking this icon &rarr; ![image](https://cdn.jsdelivr.net/npm/docsify-darklight-theme@latest/icons/sun.svg)
3. Now you can see the website's text is hard to read.

**Screenshots**

![image](https://user-images.githubusercontent.com/74750414/192426231-6750ab15-984a-4801-bd16-8884c09230af.png)

**Additional context**
This is because of the misconfiguration of `darklightTheme` config on the `main.js` file.

**Comment by hasnainmakada-99** [comment]
Hey @vikasganiga05 I would like to work on this issue

**Comment by tejask1730** [comment]
i would like to resolve this issue ? can I.

**Comment by vikasganiga05** [comment]
> Hey @vikasganiga05 I would like to work on this issue

Sure, feel free to work on it.

**Comment by vikasganiga05** [comment]
> i would like to resolve this issue ? can I.

Sorry @tejask1730 , @hasnainmakada-99 was the first to ask. Please look for some other issues or you can help him. Thank You :pray:
