### ISSUE TITLE
Display picture missing and wrong text alignment.

### ISSUE THREAD

**Issue by soumdatta81** [collab-community/journey-book#185]
**Describing the bug**
The bug is in a profile where the user's display picture is missing. Also, because of the text alignment, affects the looks of the website(screenshot attached below).

**To Reproduce**
1. Go to the [Website](https://collab-community.github.io/journey-book/#/)
2. Scroll down.
3. Look for the "Sneha Agarwal" profile
4. See the error

**Expected behavior**
To look normally like the other profiles

**Screenshots**
https://imgur.com/a/UT5mWwt

**Desktop:**
 - OS: macOS
 - Browser: Brave 
 - Version: 1.44.108 Chromium: 106.0.5249.103 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by vikasganiga05** [comment]
Thanks for reporting this issue! it has been fixed and the changes are available in this pull request: #187 . Please let me know if everything is working as expected.

Closing this issue.
