### ISSUE TITLE
Remove size badge and new status badges

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/journey-book#195]
The github-size badge is broken for some technical issues. So, remove it. Then add new badges.

> The broken badge :point_down: 

![image](https://user-images.githubusercontent.com/74750414/197134007-722403ba-a519-460f-a19a-0ffb31022561.png)

### Add new status badges

```html
<p align="center">
  <a href="https://github.com/collab-community/journey-book/graphs/contributors">
    <img src="https://img.shields.io/github/contributors/collab-community/journey-book" alt="Contributors" />
  </a>
  <a href="https://github.com/collab-community/journey-book/pulse">
    <img src="https://img.shields.io/github/commit-activity/m/collab-community/journey-book" alt="Activity" />
  </a>
  <a href="https://choosealicense.com/licenses/mit/">
    <img src="https://img.shields.io/badge/License-MIT-yellow.svg" alt="MIT License" />
  </a>
  <a href="https://discord.gg/PGadh3Vyuv">
    <img src="https://img.shields.io/discord/927781725159977013?logo=discord" alt="Chat on Discord" />
  </a>
  <a href="https://twitter.com/intent/follow?screen_name=collab__">
    <img src="https://img.shields.io/twitter/follow/collab__?style=social&logo=twitter" alt="Follow on Twitter" />
  </a>
</p>
```

> It looks like this :point_down: 

![image](https://user-images.githubusercontent.com/74750414/197136614-a125f650-8838-494f-88c4-3aeb747a8919.png)

**Comment by itsmanojthapa** [comment]
assign me this issue

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @vikasganiga05  kindly assign this issue to me so i can work on it

**Comment by vikasganiga05** [comment]
> assign me this issue

Go ahead. It's assigned to you.

**Comment by vikasganiga05** [comment]
> 

It's assigned to Manoj. He was first. You can work on other issues Thanks!

**Comment by vikasganiga05** [comment]
> Hi @vikasganiga05 kindly assign this issue to me so i can work on it

It's assigned to Manoj. He was first. You can work on other issues Thanks!
