### ISSUE TITLE
Issue with security workflows

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#28]
Unlike my repo, when added the workflows it shows this, this repo is showing that it's not been added yet, even though the workflow has been added and it's failing builds

My repo: 
![image](https://user-images.githubusercontent.com/84712013/157608462-c8c534cc-6767-41ac-b569-4eb5896a166f.png)

This repo:
![image](https://user-images.githubusercontent.com/84712013/157608503-84f8562c-27e1-4055-988b-b1a5f7c1829c.png)

I've added the exact same things in my repo.

**Comment by Adarsh-jaiss** [comment]
-- how can i fix this ? do you have any clue?

**Comment by KendallDoesCoding** [comment]
> -- how can i fix this ? do you have any clue?

Nope, tried making a PR to fix it, but it didn't work so reverted....

**Comment by Adarsh-jaiss** [comment]
should we delete that
and readd it ?

**Comment by Adarsh-jaiss** [comment]
-- recheck that , i have made some changes from settings. hope it will be fixed now :)

**Comment by KendallDoesCoding** [comment]
> -- recheck that , i have made some changes from settings. hope it will be fixed now :)

no it aren't fixed.

**Comment by Adarsh-jaiss** [comment]
please check this out : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow

**Comment by KendallDoesCoding** [comment]
> please check this out : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow

Can't understand this.... Usually, I make the security policy's and workflows from that menu only and it works well.

**Comment by Adarsh-jaiss** [comment]
-- try re- adding it:)

**Comment by KendallDoesCoding** [comment]
> -- try re- adding it:)

Ok will do.

**Comment by KendallDoesCoding** [comment]
@Adarsh-jaiss Please confirm if this is fixed. I believe it is.

cc: @collab-community/mantainers

**Comment by KendallDoesCoding** [comment]
Closing for now as it seems to be fixed, will reopen in future if there is a problem.
