### ISSUE TITLE
[DOCS] Add contribution guidelines

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/journey-book#29]
A quick guide on how to contribute to this project in the `CONTRIBUTING.md` file. And provide a template to add a new journey. Which will help beginners to contribute easily.

**Comment by Adarsh-jaiss** [comment]
Just go ahead and make a pr 😃

**Comment by KendallDoesCoding** [comment]
@vikasganiga05 Good idea.... We can also link the file on the website, when it gets done.

**Comment by KendallDoesCoding** [comment]
> And provide a template to add a new journey.

This is included in `README.md`

**Comment by KendallDoesCoding** [comment]
@vikasganiga05 What's the status on this.

**Comment by vikasganiga05** [comment]
> @vikasganiga05 What's the status on this.

I did not find any good template online for this. If you guys have any ideas share them. I think we can open a discussion on this topic.

**Comment by KendallDoesCoding** [comment]
We require people to make a PR, because if it's done via the website, users without GitHub accounts while make inappropriate journeys  as discussed by @TechStudent11 in #32

**Comment by vikasganiga05** [comment]
> > And provide a template to add a new journey.
> 
> What do you mean by this?

It's a markdown template file like an issue template. Which helps users to add their journey easily.
