### ISSUE TITLE
[STYLE] Separate css styles into an external style sheet

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/journey-book#50]
**Is your feature request related to a problem? Please describe.**
Hi, My suggestion is to separate CSS in the `index.html` file into a CSS file called `style.css`. It will make CSS cleaner and more organized.

**Screenshot**

![image](https://user-images.githubusercontent.com/74750414/180324575-18b27503-71f2-4786-b058-bc80fa168f95.png)

**Comment by ivanetra** [comment]
Hi @vikasganiga05, could u assign the issue to me?

**Comment by KendallDoesCoding** [comment]
Good idea.

**Comment by vikasganiga05** [comment]
> Hi @vikasganiga05, could u assign the issue to me?

Hi, This issue is assigned to you now. If you need any help let me know.

**Comment by sambhavgupta0705** [comment]
Hey ,is this issue resolved??

**Comment by ivanetra** [comment]
Thank you @vikasganiga05! Sorry, I've just read the comment. I want to start to resolve it

**Comment by KendallDoesCoding** [comment]
Hi Sambhav, not yet but someone is working on it!
