### ISSUE TITLE
[FEAT] Swap Journeys and Pages section on sidebar

### ISSUE THREAD

**Issue by vikasganiga05** [collab-community/journey-book#62]
**Is your feature request related to a problem? Please describe.**
Hi, my suggestion is to swap the `Journeys` and `Pages` sections on the sidebar. Because when a new user visits the website the links under the `Pages` section help the user to know more about the project. What are your thoughts folks?

**Screenshot**

![image](https://user-images.githubusercontent.com/74750414/180699336-92ff8504-d7a8-4c0f-95d6-4c3717729219.png)

**Comment by Adarsh-jaiss** [comment]
-- I totaly agree with you vikas , swamp this 👍🏻 
-- one thing I would like to add , kindly checkout Ebuka's journey .. there's an error

**Comment by KendallDoesCoding** [comment]
Yes. Will do this.

**Comment by vikasganiga05** [comment]
Thanks, Kendall.
