### ISSUE TITLE
style: Grammar mistakes in README file

### ISSUE THREAD

**Issue by Ebukachuqz** [collab-community/journey-book#68]
While reading the README file, i noticed som grammar mistakes, which if corrected, would enhance the readability of the README.md file.

It would also help others to better understand and read the procedures to joining our community. Screenshots below

![Screenshot from 2022-07-26 14-24-24](https://user-images.githubusercontent.com/31506237/181020128-90aeb8cc-8794-4e68-8650-626eb6af2c0d.png)
- This should be "a small" or "a little"

![Screenshot from 2022-07-26 14-25-45](https://user-images.githubusercontent.com/31506237/181020300-81d26959-9399-4e3a-a893-1a5f2d559eea.png)
![Screenshot from 2022-07-26 14-24-54](https://user-images.githubusercontent.com/31506237/181020325-516eb182-53fc-4a5b-a968-028be76d14b1.png)
- Punctuation marks are missing in this sections. And a few word choices, could be corrected.

**Comment by Adarsh-jaiss** [comment]
-- kindly work on this issue and fix this

**Comment by Ebukachuqz** [comment]
Alright. Will do

**Comment by 05e** [comment]
my pull fixes most of the english, except for the camo image

**Comment by Ebukachuqz** [comment]
Alright, I'll review for you
