### ISSUE TITLE
Improve the position of the dark/light theme toggler button in mobile devices

### ISSUE THREAD

**Issue by developer-diganta** [collab-community/journey-book#70]
**Describe the bug**
The theme toggler button is very close to text in case of mobile devices. 

**To Reproduce**
Open website in mobile view

**Expected behavior**
A little space between text and button would look good.

**Screenshots**
Current State:
![image](https://user-images.githubusercontent.com/65999534/181605259-9b99fcc6-aa50-4653-8667-d02a7fdbb5c5.png)
Expected State:
![image](https://user-images.githubusercontent.com/65999534/181605177-cb3547cc-1f98-4ae3-91dd-e1624fe23524.png)

**Comment by developer-diganta** [comment]
Can I work on this?

**Comment by Adarsh-jaiss** [comment]
-- yes you can work on this.. But before doing that.. Kindly check it out in your laptop and then decide the position

**Comment by developer-diganta** [comment]
@Adarsh-jaiss Can you please tell me how to edit the CSS?

**Comment by Abhinavkar** [comment]
@Adarsh-jaiss assign me with part. @developer-diganta if you would like to ?

**Comment by Abhinavkar** [comment]
#70 We need Change the css of the logo <div id="docsify-darklight-theme"> Top : 5px to top:8px for the mobile view

**Comment by KendallDoesCoding** [comment]
> @Adarsh-jaiss Can you please tell me how to edit the CSS?

this should be it? https://github.com/collab-community/journey-book/blob/main/style.css

**Comment by KendallDoesCoding** [comment]
> @Adarsh-jaiss assign me with part. @developer-diganta if you would like to ?

Will assign you if @developer-diganta is fine with it :)!

**Comment by developer-diganta** [comment]
@KendallDoesCoding yeah sure if @Abhinavkar wants it!

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding yeah sure if @Abhinavkar wants it!

Yes, he wants to work alongside with you, ig.

**Comment by KendallDoesCoding** [comment]
Any update on this @developer-diganta @Abhinavkar?
