### ISSUE TITLE
List all journey's in sidebar, make text for sidebar VERY tiny just enough for name to be seen

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#77]
A few journey's are not visible in sidebar, please fix the issue and make the text in sidebar very small so there's place for atleast 25-30 journey's for now.

Please work on this @vikasganiga05 

cc: @Adarsh-jaiss

**Comment by TechStudent11** [comment]
I do not recommend this. Instead, there should be a page with all the journeys. Also I think you should rethink about #46.

**Comment by KendallDoesCoding** [comment]
> I do not recommend this. Instead, there should be a page with all the journeys. Also I think you should rethink about #46.

There is already a page with all the journeys which is: https://collab-community.github.io/journey-book/ but there is also a sidebar.

Will discuss with @Adarsh-jaiss and @Vrashabh-Sontakke and team and let you know at the earliest.

**Comment by vikasganiga05** [comment]
Some journeys are not showing in the sidebar because of the branch protection. The `main` branch is protected so the gh-action failed to update the sidebar. I don't know how to tackle this issue. Does anyone know the solution please share?

**Comment by KendallDoesCoding** [comment]
Ooh. Then can the gh-actions make a PR or something?
