### ISSUE TITLE
[FEAT] Add favicon as profile picture of user for journey's on website

### ISSUE THREAD

**Issue by KendallDoesCoding** [collab-community/journey-book#93]
This will be hard to implement but it's just a idea: I was thinking as the favicon for people's journeys we can add their profile picture, listed in Data.json

Is this possible @vikasganiga05?

cc: @Adarsh-jaiss

**Comment by vikasganiga05** [comment]
This feature may be possible I have to do some research on this.

**Comment by Abhinavkar** [comment]
> This feature may be possible I have to do some research on this.

i think we could use event and props property and try it out Ig

**Comment by KendallDoesCoding** [comment]
Can you make a PR?

**Comment by AzeezTM** [comment]
I will like to try it out to

**Comment by vikasganiga05** [comment]
> I will like to try it out to

Okay, If you need any help feel free to ask here or on [Discord Server](https://discord.gg/PGadh3Vyuv).

**Comment by KendallDoesCoding** [comment]
Sure! Feel free to do it. Please make a PR

**Comment by AzeezTM** [comment]
How can I make a PR?

**Comment by KendallDoesCoding** [comment]
> How can I make a PR?

- Fork the repo
- Create a branch in your fork
- Do the required changes to fix this issue
- Create a PR following:  https://opensource.pradumnasaraf.co/#/pages/How-to/guide/creating-pr

**Comment by vikasganiga05** [comment]
#### Hi, here is my solution for this feature :point_down: 
Preview &nbsp; &rarr; &nbsp; https://deploy-preview-3--neontuts-docsify-test.netlify.app/
Code &nbsp; &nbsp; &nbsp; &rarr; &nbsp; https://github.com/neontuts/journey-book/tree/93-feat-dynamic-favicon

**Comment by KendallDoesCoding** [comment]
Ayy, works really well, but instead of the square in the background can it
just be the image of the user, if that's not possible, no worries. Please
make a PR. Thanks!

**Comment by vikasganiga05** [comment]
> 

Thanks, The favicons will change according to the user's avatar they provided in the `Data.json`. If find a way to modify the image I will do that else I will make the PR. Thank You :pray:

**Comment by KendallDoesCoding** [comment]
Ok thanks. Please close this issue.
